/*
 * generated by Xtext
 */
package xtend;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RecursiveStandaloneSetup extends RecursiveStandaloneSetupGenerated{

	public static void doSetup() {
		new RecursiveStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

