/*
 * generated by Xtext
 */
package xtend;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RecursiveRuntimeModule extends xtend.AbstractRecursiveRuntimeModule {

}
