/*
 * generated by Xtext
 */
package xtend;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RecursiveUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return xtend.ui.internal.RecursiveActivator.getInstance().getInjector("xtend.Recursive");
	}
	
}
