/**
 * generated by Xtext
 */
package xtend.ui.contentassist;

import xtend.ui.contentassist.AbstractRecursiveProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RecursiveProposalProvider extends AbstractRecursiveProposalProvider {
}
