/*
 * generated by Xtext
 */
package xtend.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtend.services.RecursiveGrammarAccess;

public class RecursiveParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RecursiveGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected xtend.parser.antlr.internal.InternalRecursiveParser createParser(XtextTokenStream stream) {
		return new xtend.parser.antlr.internal.InternalRecursiveParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public RecursiveGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RecursiveGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
