/*
 * generated by Xtext
 */
package xtend.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import xtend.ui.internal.RecursiveActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RecursiveExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RecursiveActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RecursiveActivator.getInstance().getInjector(RecursiveActivator.XTEND_RECURSIVE);
	}
	
}
