/*
 * generated by Xtext
 */
package xtend.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RecursiveUiModule extends xtend.ui.AbstractRecursiveUiModule {
	public RecursiveUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
