/**
 * generated by Xtext
 */
package xtend.validation;

import xtend.validation.AbstractRecursiveValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RecursiveValidator extends AbstractRecursiveValidator {
}
